services:
  - type: web
    name: Bhure-sales-and-corporation
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn web_app:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.7"
